/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brun
 */
public class Medidor extends java.applet.Applet {

    /**
     * Initializes the applet Medidor
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Subtitle = new javax.swing.JLabel();
        Days = new javax.swing.JSpinner();
        Calculate = new javax.swing.JButton();
        Hours = new javax.swing.JLabel();
        Minutes = new javax.swing.JLabel();
        Seconds = new javax.swing.JLabel();
        HoursAns = new javax.swing.JLabel();
        MinutesAns = new javax.swing.JLabel();
        SecondsAns = new javax.swing.JLabel();

        Title.setFont(new java.awt.Font("TlwgMono", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(44, 44, 44));
        Title.setText("Horas - Minutos y Segundos");

        Subtitle.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        Subtitle.setForeground(new java.awt.Color(44, 44, 44));
        Subtitle.setText("Ingrese la cantidad de dias");

        Calculate.setText("CALCULAR");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        Hours.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Hours.setForeground(new java.awt.Color(44, 44, 44));
        Hours.setText("Horas :");

        Minutes.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Minutes.setForeground(new java.awt.Color(44, 44, 44));
        Minutes.setText(" Minutos :");

        Seconds.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Seconds.setForeground(new java.awt.Color(44, 44, 44));
        Seconds.setText("Segundos :");

        HoursAns.setForeground(new java.awt.Color(44, 44, 44));

        MinutesAns.setForeground(new java.awt.Color(44, 44, 44));

        SecondsAns.setForeground(new java.awt.Color(44, 44, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(Subtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Hours)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Seconds)
                                .addGap(54, 54, 54)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MinutesAns)
                            .addComponent(SecondsAns)
                            .addComponent(HoursAns))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Title)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Calculate)
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subtitle)
                    .addComponent(Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Calculate)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoursAns)
                    .addComponent(Hours, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Minutes)
                    .addComponent(MinutesAns))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seconds)
                    .addComponent(SecondsAns))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        // TODO add your handling code here:
        int Day= (Integer)Days.getValue();
        
        int Hours=Day*24;
        HoursAns.setText(String.valueOf(Hours));
        
        int Minutes=Hours*60;
        MinutesAns.setText(String.valueOf(Minutes));
        
        int Seconds=Minutes*3600;
        SecondsAns.setText(String.valueOf(Seconds));
          
    }//GEN-LAST:event_CalculateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculate;
    private javax.swing.JSpinner Days;
    private javax.swing.JLabel Hours;
    private javax.swing.JLabel HoursAns;
    private javax.swing.JLabel Minutes;
    private javax.swing.JLabel MinutesAns;
    private javax.swing.JLabel Seconds;
    private javax.swing.JLabel SecondsAns;
    private javax.swing.JLabel Subtitle;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
